spring.application.name=Spring Boot Hello World
database.url=jdbc:sqlite:C:\\work\\training\\java\\users.db


spring.datasource.url=jdbc:sqlite:C:\\work\\training\\java\\users.db
spring.datasource.driver-class-name=org.sqlite.JDBC

logging.level.ie.pt.springboothelloworld=DEBUG